name: Build a-shell IPA

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3.5.3
      with:
        submodules: recursive

    - name: Update Submodules
      run: |
        git submodule init
        git submodule deinit -f -- cpython
        git rm -f cpython
        rm -rf .git/modules/cpython/
        git submodule add --force https://github.com/holzschu/cpython.git cpython

    - name: Install dependencies
      run: |
        sudo xcode-select --install
        chmod +x ./downloadFrameworks.sh
        ./downloadFrameworks.sh
        cd cpython
        chmod +x ./downloadAndCompile.sh
        sh ./downloadAndCompile.sh
        cd ..

    - name: Build and archive app
      run: |
        xcodebuild -scheme a-Shell -configuration Release -archivePath a-Shell.xcarchive archive
        xcodebuild -exportArchive -archivePath a-Shell.xcarchive -exportPath a-Shell -exportOptionsPlist ExportOptions.plist
    
    - name: Rename .xcarchive to .ipa
      run: |
        mv a-Shell.xcarchive/Products/Applications/*.app a-Shell.ipa

    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: a-Shell
        path: a-Shell.ipa
