name: Build a-shell project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Fix submodule issue
      run: |
        git submodule deinit -f cpython/packages/rasterio
        rm -rf .git/modules/cpython/packages/rasterio
        git rm -f cpython/packages/rasterio
        git submodule add -b master https://github.com/rasterio/rasterio.git cpython/packages/rasterio

    - name: Install dependencies
      run: |
        sudo xcode-select --install
        chmod +x ./downloadFrameworks.sh
        ./downloadFrameworks.sh
        cd cpython
        chmod +x ./downloadAndCompile.sh
        sh ./downloadAndCompile.sh
        cd ..

    - name: Build and archive app
      run: |
        xcodebuild -scheme a-Shell -configuration Release -archivePath a-Shell.xcarchive archive
        xcodebuild -exportArchive -archivePath a-Shell.xcarchive -exportPath a-Shell -exportOptionsPlist ExportOptions.plist
    
    - name: Rename .xcarchive to .ipa
      run: |
        mv a-Shell.xcarchive/Products/Applications/*.app a-Shell.ipa

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: a-Shell
        path: a-Shell.ipa
