name: Build a-shell project lol

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Update submodules
      run: |
        git submodule sync --recursive
        git submodule update --init --recursive --remote

    - name: Fix submodule issue
      run: |
        cd cpython/packages
        git clone --depth 1 https://github.com/rasterio/rasterio.git

    - name: Install dependencies
      run: |
        sudo xcode-select --install
        chmod +x ./downloadFrameworks.sh
        ./downloadFrameworks.sh
        cd cpython
        chmod +x ./downloadAndCompile.sh
        sh ./downloadAndCompile.sh
        cd ..

    - name: Build and archive app
      run: |
        xcodebuild -scheme a-Shell -configuration Release -archivePath a-Shell.xcarchive archive
        xcodebuild -exportArchive -archivePath a-Shell.xcarchive -exportPath a-Shell -exportOptionsPlist ExportOptions.plist

    - name: Rename .xcarchive to .ipa
      run: |
        mv a-Shell.xcarchive/Products/Applications/*.app a-Shell.ipa

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: a-Shell
        path: a-Shell.ipa
